#!/usr/bin/env bash
# Creates an nginx web sever
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw app list
sudo ufw enable
sudo ufw allow 'Nginx HTTPS'
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'Nginx Full'
sudo ufw status
sudo chmod u+x /var/www/html/index.nginx-debian.html
sudo echo "Hello world" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
